FROM node:12

WORKDIR ./

ENV DB_HOST $PRO_DB_HOST
ENV DB_PORT $PRO_DB_PORT
ENV DB_USER $PRO_DB_USER
ENV DB_PASSWORD $PRO_DB_PASSWORD
ENV DB_NAME $PRO_DB_NAME
ENV SERVER_PORT $PRO_SERVER_PORT
ENV JWT_SECRET $JWT_SECRET

COPY ./schnauzer/package*.json ./

RUN npm ci
RUN npm i -g typescript

COPY ./schnauzer .

EXPOSE 8080
RUN npm start