name: CD

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: fqwjo
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
      - uses: actions/checkout@v2

      - name: docker image build
        run: docker build -t schnauzer .

      - name: upload to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: schnauzer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}