name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.3]

    steps:
      - uses: actions/checkout@v2
        
      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Dependencies Installation
        run: npm ci
        working-directory: ./schnauzer
        
      - name: build
        run: npm run build
        working-directory: ./schnauzer
