name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        node-version: [12.16.3]

    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Installation
        run: npm ci
        working-directory: ./schnauzer

      - name: build
        run: npm run build
        working-directory: ./schnauzer

      - name: install codecov
        run: npm i -g codecov

      - name: test
        run: npm run cover
        working-directory: ./schnauzer

      - name: report
        run: npm run report
        working-directory: ./schnauzer

      - name: codecov
        run: codecov
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: docker image build
        run: docker build -t schnauzer .

      - name: upload to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: schnauzer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}