# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        node-version: [12.16.3]

    steps:
      - uses: actions/checkout@v2
        
      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Dependencies Installation
        run: npm ci
        working-directory: ./schnauzer
        
      - name: build
        run: npm run build
        working-directory: ./schnauzer

      - name: install codecov
        run: npm i -g codecov

      - name: test
        run: npm run cover
        working-directory: ./schnauzer

      - name: report
        run: npm run report
        working-directory: ./schnauzer
        
      - name: codecov
        run: codecov